name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os.host }}
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
        os:
          - name: ubuntu
            host: ubuntu-latest
          - name: windows
            host: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.13 # Specify the version of Poetry you want to use

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create false

      - name: Install Dependencies
        run: poetry install

      - name: Test with pytest
        run: |
          poetry run pytest tests/ --verbose
