name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os.host }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
        os:
          - name: ubuntu
            host: ubuntu-latest
          - name: windows
            host: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1.3
        with:
          version: 1.2.0 # Specify the Poetry version to use

      - name: Cache Poetry virtual environment
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            !~/.cache/pypoetry/artifacts
            !~/.cache/pypoetry/repositories
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: |
          poetry install --no-root  # Install dependencies as defined in pyproject.toml

      - name: Download spaCy model
        run: |
          poetry run python -m spacy download en_core_web_sm

      - name: Test with pytest
        run: |
          poetry run pytest tests/ --verbose
